apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: product-service:0.0.4  # Use the local image
        imagePullPolicy: Never  # Do not pull from a registry specific for local docker images
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "postgresql.data.svc.cluster.local"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: microservice-secret
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microservice-secret
              key: db_password
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"